[
  {
    img: "/Images/Dress/1.webp",
    name: "Dress 1",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "dress",
    target: "female",
  },
  {
    img: "/Images/Dress/2.jpg",
    name: "Dress 2",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "dress",
    target: "female",
  },
  {
    img: "/Images/Dress/23.jpg",
    name: "Dress 3",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "dress",
    target: "female",
  },
  {
    img: "/Images/Dress/4.jpg",
    name: "Dress 4",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "dress",
    target: "female",
  },
  {
    img: "/Images/Dress/4.webp",
    name: "Dress 4",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "dress",
    target: "female",
  },
  {
    img: "/Images/Hoodie/1.webp",
    name: "Hoodie 1",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "Hoodie",
    target: "all",
  },
  {
    img: "/Images/Hoodie/2.webp",
    name: "Hoodie 2",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "Hoodie",
    target: "all",
  },
  {
    img: "/Images/Hoodie/3.jpg",
    name: "Hoodie 3",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "Hoodie",
    target: "all",
  },
  {
    img: "/Images/Hoodie/4.jpg",
    name: "Hoodie 4",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "Hoodie",
    target: "all",
  },
  {
    img: "/Images/Hoodie/5.jpg",
    name: "Hoodie 5",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "Hoodie",
    target: "all",
  },
  {
    img: "/Images/Hoodie/6.jpg",
    name: "Hoodie 6",
    price: 200,
    desc: "This innovative product is designed to revolutionize the way you",
    category: "Hoodie",
    target: "all",
  },
];
